### ISSUE TITLE
NullPointerException using Netbeans 6.7 beta

### ISSUE THREAD

**Issue by nightscape** [QuBiT/cucumber-netbeans-plugin#1]
Hi Roland,

I have the honor of posting the first issue ;)
There is a NPE for your very nice looking plugin using Netbeans 6.7 beta:

```
   org.netbeans.modules.parsing.spi.ParseException
at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:191)
at org.netbeans.modules.parsing.api.ParserManager.parse(ParserManager.java:99)
at org.netbeans.modules.languages.features.CompletionProviderImpl$CompletionTaskImpl$1.run(CompletionProviderImpl.java:357)
at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:573)
at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:1005)
    Caused by: java.lang.NullPointerException
at org.netbeans.modules.languages.features.CompletionProviderImpl$CompletionTaskImpl.addParserTags(CompletionProviderImpl.java:376)
at org.netbeans.modules.languages.features.CompletionProviderImpl$CompletionTaskImpl.access$300(CompletionProviderImpl.java:185)
at org.netbeans.modules.languages.features.CompletionProviderImpl$CompletionTaskImpl$1$1.run(CompletionProviderImpl.java:362)
at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:129)
at org.netbeans.modules.parsing.api.ParserManager$UserTaskAction.run(ParserManager.java:113)
at org.netbeans.modules.parsing.impl.TaskProcessor.runUserTask(TaskProcessor.java:189)
... 4 more
```

**Comment by QuBiT** [comment]
Oh noooo ;)

But looking at this trace it does not seem to be a problem of my plugin, it looks like a netbeans problem, but if not, i'll try to solve it in this week.

**Comment by nightscape** [comment]
Ok, that might well be. I thought that org.netbeans.modules.languages.features was  the namespace of your plugin...
The plug-in does not highlight the file in my case, but that might be a problem with the other Cucumber plug-in I had installed.
If I figure out the problem I'll post it here for other people having the same problem.
Best regards!

**Comment by QuBiT** [comment]
I tried Version 1.1.8 with Netbeans 6.7 RC2 and it works without any exception.

**Comment by nightscape** [comment]
Verified :)
